# Generated by Django 5.2.3 on 2025-06-19 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyprofile',
            name='course',
        ),
    ]
