# Generated by Django 5.2.3 on 2025-06-18 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('users', '0003_studentprofile_aadhar_number_studentprofile_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course'),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='student_profiles/'),
        ),
    ]
