# Generated by Django 5.2.3 on 2025-06-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_facultyprofile_course_facultyprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='faculty_profiles/'),
        ),
    ]
