# Generated by Django 5.2.3 on 2025-06-18 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
