# Generated by Django 5.2.3 on 2025-06-20 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentEnrollment',
        ),
    ]
