# Generated by Django 5.2.3 on 2025-06-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentEnrollment',
        ),
    ]
